server {
    listen 8097;
    listen [::]:8097;

    server_name _;

    root /var/www/html/public;

    index index.php index.html;

    charset utf-8;

    client_max_body_size 100M;


    # =====================================================
    # LARAVEL
    # =====================================================
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }


    # =====================================================
    # FAVICON
    # =====================================================
    location = /favicon.ico {
        access_log off;
        log_not_found off;
    }


    # =====================================================
    # ROBOTS
    # =====================================================
    location = /robots.txt {
        access_log off;
        log_not_found off;
    }


    # =====================================================
    # PHP
    # =====================================================
    location ~ \.php$ {
        try_files $uri =404;

        fastcgi_pass 127.0.0.1:9000;

        fastcgi_index index.php;

        include fastcgi_params;

        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $document_root;
    }


    # =====================================================
    # BLOCK HIDDEN FILES
    # =====================================================
    location ~ /\.(?!well-known).* {
        deny all;
    }
}